pygments:       true
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md
    - Rakefile

title:          LeafGrass
url:            http://librae8226.github.com
feed:           /atom.xml
description:    "librae projects"
comment:        Keep It Simple Stupid

author:
    name:       Librae
    email:      librae8226@gmail.com

about: >
    I'm Librae, a <a href="http://github.com/LeafGrass">LeafGrass</a> developer
    and embedded programming lover. You can fork me on <a href="http://github.com/librae8226">GitHub</a>.

disqus:
    id:         librae8226

nav:
    - name:     Home
      url:      /

    - name:     Projects
      url:      /
      subnav:
        - name: Ousia
          url:  /ousia/
        - name: QuadroCopter
          url:  /quadrocopter/

    - name:     Blog
      url:      /

    - name:     Portfolio
      url:      /portfolio/

    - name:     About
      url:      /about/
      subnav:
        - name: Contact
          url:  mailto:librae8226-at-dotcom-after-gmail


footer:
    - verb:     Thinking
      action:   How can this world work without a centrum?

    - verb:     Digging
      action:   The ousia of our nature.

copyright:
    - Design by <a href="http://ipsleung.com">Iris Leung</a>.
    - Copyright (C) 2010, <a href="http://appden.com">Scott Kyle</a>. All Rights Reserved.
    - Copyright (C) 2011, <a href="http://leafgrass.tk">Librae</a>. All Rights Reserved.

css:
    - /lib/appden.css
    - /lib/syntax.css

js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
